# Generated by Django 5.0.4 on 2024-04-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_comment_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
