# Generated by Django 5.0.4 on 2024-05-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_followers_follower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
    ]
