# Generated by Django 5.0.4 on 2024-05-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_options_remove_like_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
