# Generated by Django 5.0.3 on 2024-04-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_comment_options_comment_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="active",
        ),
    ]
